import copy
import json
from django.test import Client
from test_cards import BaseCardInserter

from cuesbey_main.cube_diff.models import get_cards_from_names


class ViewTest(BaseCardInserter):

    def post_to_card_contents(self, data, client=None):
        """
        utility method of posting data to card contents
        :param data: the data that will be interpreted as json
        :param client: if provided, a Django test client that should be used,
            else, a new one will be created
        :return: the results of the POST
        """
        client = client or Client()

        return client.post('/card_contents/', json.dumps(data), "text/json",
                           HTTP_X_REQUESTED_WITH='XMLHttpRequest')

    def make_diff_data(self, before, after=None):
        """
        utility method for constructing a dictionary in the form expected from
        the cube_diff app

        :param before: list of string card names
        :param after: list of string card names, defaults to before
        :return: dict in the expected form
        """

        return {
            "card_names": {
                "before": before,
                "after": after or copy.deepcopy(before)}
        }

    @property
    def mtgo_og_cube(self):
        return [
            'Absorb',
            'Abyssal Persecutor',
            'Academy Rector',
            'Academy Ruins',
            'Acidic Slime',
            'Act of Aggression',
            'Aeon Chronicler',
            'AEther Adept',
            'AEther Vial',
            'Aftershock',
            'Agony Warp',
            'Ajani Goldmane',
            'Ajani Vengeant',
            'Akroma, Angel of Fury',
            'Akroma, Angel of Wrath',
            "Akroma's Vengeance",
            'All Is Dust',
            "Ambition's Cost",
            'Ancestral Vision',
            'Ancient Grudge',
            'Ancient Tomb',
            'Angel of Despair',
            'Angelic Destiny',
            'Animate Dead',
            'Ankh of Mishra',
            'Arbor Elf',
            'Arc Lightning',
            'Arc Trail',
            'Arid Mesa',
            'Armageddon',
            'Augury Adept',
            "Avacyn's Pilgrim",
            'Avalanche Riders',
            'Aven Mindcensor',
            'Avenger of Zendikar',
            'Awakening Zone',
            'Badlands',
            'Balance',
            'Ball Lightning',
            'Bane of the Living',
            'Banefire',
            'Baneslayer Angel',
            'Bant Charm',
            'Barbarian Ring',
            'Basalt Monolith',
            'Basilisk Collar',
            'Batterskull',
            'Bayou',
            'Beacon of Destruction',
            'Beast Within',
            'Behemoth Sledge',
            'Birds of Paradise',
            'Birthing Pod',
            'Bitterblossom',
            'Bituminous Blast',
            'Black Knight',
            'Black Vise',
            'Blade Splicer',
            'Blastoderm',
            'Blistering Firecat',
            'Blood Crypt',
            'Blood Knight',
            'Bloodbraid Elf',
            'Bloodghast',
            'Bloodgift Demon',
            'Bloodstained Mire',
            'Blue Elemental Blast',
            'Bogardan Hellkite',
            'Boggart Ram-Gang',
            'Bone Shredder',
            'Braids, Cabal Minion',
            'Brainstorm',
            'Breeding Pool',
            'Brimstone Volley',
            'Brine Elemental',
            'Brooding Saurian',
            'Broodmate Dragon',
            'Buried Alive',
            'Burning of Xinye',
            'Burrenton Forge-Tender',
            'Cabal Coffers',
            'Calciderm',
            'Call of the Herd',
            'Call the Skybreaker',
            'Capsize',
            'Careful Consideration',
            'Carnophage',
            'Cataclysm',
            'Catastrophe',
            'Celestial Colonnade',
            'Celestial Purge',
            'Chain Lightning',
            'Chameleon Colossus',
            'Chandra Nalaar',
            'Chandra, the Firebrand',
            "Chandra's Phoenix",
            'Channel',
            'Chaos Warp',
            'Char',
            'Chrome Mox',
            'City of Traitors',
            'Clifftop Retreat',
            'Cloudgoat Ranger',
            'Cloudthresher',
            'Coalition Relic',
            'Cold-Eyed Selkie',
            'Coldsteel Heart',
            'Compulsive Research',
            'Condemn',
            'Consecrated Sphinx',
            'Consuming Vapors',
            'Control Magic',
            'Corpse Dance',
            'Counterspell',
            'Countryside Crusher',
            'Court Hussar',
            'Creakwood Liege',
            'Creeping Tar Pit',
            'Crucible of Worlds',
            'Cruel Ultimatum',
            'Cryptic Command',
            'Cultivate',
            'Cursecatcher',
            'Cursed Scroll',
            'Damnation',
            'Dark Confidant',
            'Dark Ritual',
            'Dauthi Horror',
            'Dauthi Marauder',
            'Dauthi Slayer',
            'Day of Judgment',
            'Daybreak Ranger',
            'Daze',
            'Death Cloud',
            'Deathmark',
            'Decree of Justice',
            'Deep Analysis',
            'Demonic Tutor',
            'Deprive',
            'Deranged Hermit',
            'Desertion',
            'Despise',
            'Destructive Force',
            'Devastating Dreams',
            "Devil's Play",
            'Devoted Druid',
            'Diabolic Servitude',
            'Diregraf Ghoul',
            'Disenchant',
            'Disfigure',
            'Dismantling Blow',
            'Dismember',
            'Dismiss',
            'Dissipate',
            'Doom Blade',
            'Doran, the Siege Tower',
            'Dragonskull Summit',
            'Dream Halls',
            'Drogskol Reaver',
            'Drowned Catacomb',
            'Duress',
            'Earthquake',
            'Edric, Spymaster of Trest',
            'Eight-and-a-Half-Tails',
            'Eldrazi Monument',
            'Electrolyze',
            'Elesh Norn, Grand Cenobite',
            'Elite Vanguard',
            'Elspeth Tirel',
            'Elspeth, Knight-Errant',
            'Elves of Deep Shadow',
            'Ember Hauler',
            'Emeria Angel',
            'Empty the Warrens',
            'Enclave Cryptologist',
            'Engineered Explosives',
            'Enlightened Tutor',
            'Entomb',
            'Epochrasite',
            'Esper Charm',
            'Essence Scatter',
            'Etched Oracle',
            'Eternal Dragon',
            'Eternal Witness',
            'Ethersworn Canonist',
            'Everflowing Chalice',
            'Exalted Angel',
            'Exhume',
            'Explore',
            'Fact or Fiction',
            "Faith's Fetters",
            'Falkenrath Aristocrat',
            'Farseek',
            'Fathom Seer',
            'Fauna Shaman',
            'Fellwar Stone',
            'Fertile Ground',
            'Fiend Hunter',
            'Figure of Destiny',
            'Fire Ambush',
            'Fireblast',
            'Firebolt',
            'Firemane Angel',
            'Firespout',
            'Firestorm',
            'Flametongue Kavu',
            'Flashfreeze',
            'Flickerwisp',
            'Flooded Strand',
            'Forbid',
            'Forbidden Alchemy',
            'Force of Will',
            'Force Spike',
            'Frantic Search',
            'Frenzied Goblin',
            'Frost Titan',
            'Future Sight',
            'Fyndhorn Elves',
            "Gaea's Cradle",
            'Gamble',
            'Garruk Relentless',
            'Garruk Wildspeaker',
            'Garruk, Primal Hunter',
            'Gatekeeper of Malakir',
            'Gathan Raiders',
            'Geist of Saint Traft',
            'Genesis',
            'Genesis Wave',
            'Genju of the Spires',
            "Geralf's Messenger",
            'Ghitu Encampment',
            'Giant Solifuge',
            'Gideon Jura',
            "Gideon's Lawkeeper",
            'Gifts Ungiven',
            'Gilded Lotus',
            'Glacial Fortress',
            'Glen Elendra Archmage',
            'Glorious Anthem',
            'Go for the Throat',
            'Goblin Goon',
            'Goblin Guide',
            'Goblin Legionnaire',
            'Goblin Ruinblaster',
            'Goblin Trenches',
            'Goblin Wardriver',
            'Goblin Welder',
            'Godless Shrine',
            'Grafted Wargear',
            'Grand Arbiter Augustin IV',
            'Grave Titan',
            'Graveborn Muse',
            'Gravecrawler',
            'Great Sable Stag',
            'Greater Gargadon',
            "Green Sun's Zenith",
            'Grim Backwoods',
            'Grim Lavamancer',
            'Grim Monolith',
            'Grimgrin, Corpse-Born',
            'Hallowed Burial',
            'Hallowed Fountain',
            'Harmonize',
            'Havengul Lich',
            'Heartbeat of Spring',
            "Hell's Thunder",
            'Hellspark Elemental',
            'Hero of Bladehold',
            'Hero of Oxid Ridge',
            'Hex Parasite',
            'Hinterland Harbor',
            'Hokori, Dust Drinker',
            'Honor of the Pure',
            'Huntmaster of the Fells',
            'Hymn to Tourach',
            'Hypnotic Specter',
            'Hystrodon',
            'Ideas Unbound',
            'Imperial Seal',
            'Impulse',
            'Incinerate',
            'Increasing Devotion',
            'Indrik Stomphowler',
            'Inferno Titan',
            'Ingot Chewer',
            'Ink-Eyes, Servant of Oni',
            'Innocent Blood',
            'Inquisition of Kozilek',
            'Into the Roil',
            'Intuition',
            'Iona, Shield of Emeria',
            'Isamaru, Hound of Konda',
            'Isochron Scepter',
            'Isolated Chapel',
            'Jace Beleren',
            'Jace, the Mind Sculptor',
            'Jackal Pup',
            'Jokulhaups',
            'Joraga Treespeaker',
            'Journey to Nowhere',
            'Jungle Lion',
            'Jushi Apprentice',
            'Kami of Ancient Law',
            'Karakas',
            'Kargan Dragonlord',
            'Karn Liberated',
            'Keiga, the Tide Star',
            'Keldon Champion',
            'Keldon Marauders',
            'Kira, Great Glass-Spinner',
            'Kird Ape',
            'Kitchen Finks',
            'Kjeldoran Outpost',
            'Knight of the Reliquary',
            "Kodama's Reach",
            'Kokusho, the Evening Star',
            'Korlash, Heir to Blackblade',
            'Koth of the Hammer',
            'Kozilek, Butcher of Truth',
            'Krosan Grip',
            'Lake of the Dead',
            'Land Tax',
            "Laquatus's Champion",
            'Lavaclaw Reaches',
            'Lead the Stampede',
            'Leatherback Baloth',
            "Legacy's Allure",
            'Leonin Relic-Warder',
            'Life from the Loam',
            'Lightning Bolt',
            'Lightning Greaves',
            'Lightning Helix',
            'Liliana of the Veil',
            'Liliana Vess',
            'Lingering Souls',
            "Lion's Eye Diamond",
            'Living Death',
            'Llanowar Elves',
            'Loam Lion',
            'Lodestone Golem',
            'Looter il-Kor',
            'Lotus Bloom',
            'Lotus Cobra',
            'Lotus Petal',
            'Loxodon Hierarch',
            'Loyal Cathar',
            'Loyal Retainers',
            'Lu Xun, Scholar General',
            'Luminarch Ascension',
            'Maelstrom Pulse',
            'Magma Jet',
            'Magus of the Tabernacle',
            'Makeshift Mannequin',
            "Man-o'-War",
            'Mana Leak',
            'Mana Tithe',
            'Manriki-Gusari',
            'Marsh Flats',
            'Martial Coup',
            'Master of the Wild Hunt',
            'Masticore',
            'Maze of Ith',
            'Meloku the Clouded Mirror',
            'Memory Jar',
            'Memory Lapse',
            'Mentor of the Meek',
            'Mesmeric Fiend',
            'Mikaeus, the Lunarch',
            'Mimic Vat',
            'Mind Shatter',
            'Mind Stone',
            "Mind's Desire",
            'Mindslaver',
            "Mirari's Wake",
            'Mirran Crusader',
            'Mirror Entity',
            'Miscalculation',
            "Mishra's Factory",
            'Misty Rainforest',
            'Mogg War Marshal',
            'Mold Shambler',
            'Moldervine Cloak',
            'Molten Rain',
            'Molten-Tail Masticore',
            "Moment's Peace",
            'Momentary Blink',
            'Mortarpod',
            'Mortify',
            'Mother of Runes',
            'Mox Diamond',
            'Mulldrifter',
            'Mutavault',
            'Myr Battlesphere',
            'Mystic Snake',
            'Mystical Tutor',
            'Nantuko Shade',
            'Nantuko Vigilante',
            'Narcolepsy',
            'Natural Order',
            'Naturalize',
            'Necromancy',
            'Necropotence',
            'Negate',
            'Nekrataal',
            'Neurok Commando',
            "Nevinyrral's Disk",
            'Nezumi Graverobber',
            'Nezumi Shortfang',
            'Nicol Bolas, Planeswalker',
            "Night's Whisper",
            'Nightscape Familiar',
            'Ninja of the Deep Hours',
            'Niv-Mizzet, the Firemind',
            'Noble Hierarch',
            'Nostalgic Dreams',
            'Nucklavee',
            'Obliterate',
            'Oblivion Ring',
            'Obstinate Baloth',
            'Ohran Viper',
            'Old Man of the Sea',
            'Olivia Voldaren',
            "Oona's Prowler",
            'Opportunity',
            'Opposition',
            'Opt',
            'Oracle of Mul Daya',
            'Orcish Lumberjack',
            'Oust',
            'Overgrown Battlement',
            'Overgrown Tomb',
            'Pact of Negation',
            'Paladin en-Vec',
            'Palinchron',
            'Palladium Myr',
            'Parallax Wave',
            'Path to Exile',
            'Pernicious Deed',
            'Phantasmal Bear',
            'Phantom Centaur',
            'Phyrexian Arena',
            'Phyrexian Crusader',
            'Phyrexian Metamorph',
            'Phyrexian Negator',
            'Phyrexian Obliterator',
            'Phyrexian Processor',
            'Phyrexian Rager',
            'Phyrexian Revoker',
            'Pillage',
            'Pithing Needle',
            'Plague Sliver',
            'Plateau',
            'Platinum Angel',
            'Plow Under',
            'Polluted Delta',
            'Ponder',
            'Porcelain Legionnaire',
            'Powder Keg',
            'Power Sink',
            'Precursor Golem',
            'Preordain',
            'Price of Progress',
            'Priest of Urabrask',
            'Primal Command',
            'Primeval Titan',
            'Primordial Hydra',
            'Prismatic Lens',
            'Pristine Talisman',
            'Profane Command',
            'Prophetic Bolt',
            'Psychatog',
            'Pulse of the Fields',
            'Pulse of the Forge',
            'Puppeteer Clique',
            'Putrefy',
            'Putrid Leech',
            'Pyroclasm',
            'Pyrokinesis',
            'Qasali Pridemage',
            'Quirion Dryad',
            'Raging Ravine',
            'Rampant Growth',
            'Rancor',
            'Ranger of Eos',
            'Ratchet Bomb',
            'Ravages of War',
            'Ravenous Baboons',
            'Ray of Revelation',
            'Razormane Masticore',
            'Realm Razer',
            'Reanimate',
            'Reckless Charge',
            'Recurring Nightmare',
            'Red Elemental Blast',
            'Regrowth',
            'Relic of Progenitus',
            'Remand',
            'Renewed Faith',
            'Repeal',
            'Restock',
            'Reveillark',
            'Rhox War Monk',
            'Rift Bolt',
            'Riftwing Cloudskate',
            'Rishadan Port',
            'Rofellos, Llanowar Emissary',
            'Rolling Earthquake',
            'Rootbound Crag',
            'Rorix Bladewing',
            'Rout',
            'Rude Awakening',
            'Ruhan of the Fomori',
            'Sacred Foundry',
            'Sakura-Tribe Elder',
            'Sarcomancy',
            'Sarkhan the Mad',
            'Savannah',
            'Savannah Lions',
            'Scalding Tarn',
            'Scorned Villager',
            'Scroll Rack',
            'Scrubland',
            'Sea Gate Oracle',
            'Seal of Primordium',
            'Search for Tomorrow',
            'Searing Blaze',
            'Seething Song',
            "Sensei's Divining Top",
            'Serendib Efreet',
            'Shadowmage Infiltrator',
            'Shelldock Isle',
            'Sheoldred, Whispering One',
            'Shining Shoal',
            'Show and Tell',
            'Shriekmaw',
            'Shrine of Burning Rage',
            'Siege-Gang Commander',
            'Sign in Blood',
            'Silent Specter',
            'Silver Knight',
            'Simic Sky Swallower',
            'Sinkhole',
            'Skeletal Scrying',
            'Skeletal Vampire',
            'Skinrender',
            'Skithiryx, the Blight Dragon',
            'Skizzik',
            'Skullclamp',
            'Slagstorm',
            'Slaughter Pact',
            'Slith Firewalker',
            'Smash to Smithereens',
            'Smokestack',
            'Snapcaster Mage',
            'Sneak Attack',
            'Snuff Out',
            'Solemn Simulacrum',
            'Soltari Champion',
            'Soltari Monk',
            'Soltari Priest',
            'Sorin Markov',
            'Sorin, Lord of Innistrad',
            'Sower of Temptation',
            'Spectral Lynx',
            'Spectral Procession',
            'Spell Pierce',
            'Spellskite',
            'Sphere of the Suns',
            'Sphinx of Jwar Isle',
            'Sphinx of the Steel Wind',
            'Spikeshot Elder',
            'Spiritmonger',
            'Sprouting Thrinax',
            'Staggershock',
            'Steam Vents',
            'Steppe Lynx',
            'Stifle',
            'Stillmoon Cavalier',
            'Stirring Wildwood',
            'Stomping Ground',
            'Stonecloaker',
            'Stoneforge Mystic',
            'Stonewood Invocation',
            'Stormblood Berserker',
            'Strangleroot Geist',
            'Strip Mine',
            'Stromkirk Noble',
            'Student of Warfare',
            'Stunted Growth',
            'Stupor',
            'Sulfur Falls',
            'Sulfuric Vortex',
            'Summoning Trap',
            'Sun Titan',
            'Sundering Titan',
            'Sunpetal Grove',
            'Survival of the Fittest',
            'Sword of Body and Mind',
            'Sword of Feast and Famine',
            'Sword of Fire and Ice',
            'Sword of Light and Shadow',
            'Sword of War and Peace',
            'Swords to Plowshares',
            'Sylvan Library',
            'Taiga',
            'Tainted Pact',
            'Tangle Wire',
            'Tarmogoyf',
            'Tattermunge Maniac',
            'Taurean Mauler',
            'Tectonic Edge',
            'Teetering Peaks',
            'Temple Garden',
            'Tendrils of Agony',
            'Terastodon',
            'Terminate',
            'Terror',
            'Thalia, Guardian of Thraben',
            'Thawing Glaciers',
            'Thelonite Hermit',
            'Thieving Magpie',
            'Thirst for Knowledge',
            'Thornling',
            'Thornscape Battlemage',
            'Thoughtseize',
            'Thran Dynamo',
            'Thrun, the Last Troll',
            'Thunderblust',
            'Thunderscape Battlemage',
            'Tidehollow Sculler',
            'Tidings',
            'Time Spiral',
            'Time Warp',
            'Tin Street Hooligan',
            'Tinker',
            'Tithe',
            'Tolaria West',
            'Tombstalker',
            'Tooth and Nail',
            'Torch Fiend',
            "Tormod's Crypt",
            'Tradewind Rider',
            'Treachery',
            'Treetop Village',
            'Trinket Mage',
            'Troll Ascetic',
            'Tropical Island',
            'Trygon Predator',
            'Tumble Magnet',
            'Tundra',
            'Turnabout',
            'Ulamog, the Infinite Gyre',
            "Umezawa's Jitte",
            'Underground Sea',
            'Undermine',
            'Unearth',
            'Upheaval',
            'Urabrask the Hidden',
            'Vampire Hexmage',
            'Vampire Lacerator',
            'Vampire Nighthawk',
            'Vampiric Tutor',
            'Vault of the Archangel',
            'Vedalken Shackles',
            'Vendilion Clique',
            'Vengevine',
            'Venser, Shaper Savant',
            'Venser, the Sojourner',
            'Verdant Catacombs',
            'Vesuvan Shapeshifter',
            'Vindicate',
            'Vinelasher Kudzu',
            'Vines of Vastwood',
            'Visara the Dreadful',
            'Void',
            'Voidmage Prodigy',
            'Voidslime',
            'Volcanic Fallout',
            'Volcanic Hammer',
            'Volcanic Island',
            "Volrath's Stronghold",
            'Vorapede',
            'Vulshok Refugee',
            'Wake Thrasher',
            'Wall of Blossoms',
            'Wall of Omens',
            'Wall of Reverence',
            'Wall of Roots',
            'Wasteland',
            'Waterfront Bouncer',
            'Watery Grave',
            'Weathered Wayfarer',
            'Werebear',
            'Wheel of Fortune',
            'Whipcorder',
            'White Knight',
            'Wickerbough Elder',
            'Wild Nacatl',
            'Wildfire',
            'Willbender',
            'Windbrisk Heights',
            'Windswept Heath',
            'Wispmare',
            'Wood Elves',
            'Wooded Foothills',
            'Woodfall Primus',
            'Woodland Cemetery',
            'Woolly Thoctar',
            'Worn Powerstone',
            'Worship',
            'Wrath of God',
            'Wurmcoil Engine',
            'Xiahou Dun, the One-Eyed',
            'Yavimaya Elder',
            'Yavimaya Hollow',
            "Yawgmoth's Will",
            'Yosei, the Morning Star',
            'Zo-Zu the Punisher',
            'Zombie Cutthroat'
        ]

    @property
    def mtgo_avr_cube(self):
        return [
            'Absorb',
            'Academy Rector',
            'Academy Ruins',
            'Acidic Slime',
            'Act of Aggression',
            'Aeon Chronicler',
            'AEther Vial',
            'Aftershock',
            'Agony Warp',
            'Ajani Goldmane',
            'Ajani Vengeant',
            'Akroma, Angel of Fury',
            'Akroma, Angel of Wrath',
            "Akroma's Vengeance",
            'All Is Dust',
            "All Suns' Dawn",
            'Ancestral Vision',
            'Ancient Grudge',
            'Ancient Tomb',
            'Angel of Despair',
            'Angelic Destiny',
            'Animate Dead',
            'Ankh of Mishra',
            'Arbor Elf',
            'Arc Lightning',
            'Arc Trail',
            'Arid Mesa',
            'Armageddon',
            'Augury Adept',
            'Avacyn, Angel of Hope',
            "Avacyn's Pilgrim",
            'Avalanche Riders',
            'Aven Mindcensor',
            'Avenger of Zendikar',
            'Awakening Zone',
            'Badlands',
            'Balance',
            'Ball Lightning',
            'Bane of the Living',
            'Baneslayer Angel',
            'Bant Charm',
            'Barbarian Ring',
            'Basalt Monolith',
            'Basilisk Collar',
            'Batterskull',
            'Bayou',
            'Beacon of Destruction',
            'Beast Within',
            'Birds of Paradise',
            'Birthing Pod',
            'Bitterblossom',
            'Bituminous Blast',
            'Black Knight',
            'Black Vise',
            'Blade Splicer',
            'Blastoderm',
            'Blistering Firecat',
            'Blood Crypt',
            'Blood Knight',
            'Bloodbraid Elf',
            'Bloodghast',
            'Bloodgift Demon',
            'Bloodstained Mire',
            'Blue Elemental Blast',
            'Bogardan Hellkite',
            'Boggart Ram-Gang',
            'Bone Shredder',
            'Bonfire of the Damned',
            'Braids, Cabal Minion',
            'Brain Freeze',
            'Brainstorm',
            'Breeding Pool',
            'Brimstone Volley',
            'Brine Elemental',
            'Brooding Saurian',
            'Broodmate Dragon',
            'Buried Alive',
            'Burning of Xinye',
            'Burrenton Forge-Tender',
            'Cabal Coffers',
            'Calciderm',
            'Call of the Herd',
            'Call the Skybreaker',
            'Capsize',
            'Careful Consideration',
            'Cataclysm',
            'Catastrophe',
            'Celestial Colonnade',
            'Celestial Purge',
            'Chain Lightning',
            'Chameleon Colossus',
            'Chandra Nalaar',
            'Chandra, the Firebrand',
            "Chandra's Phoenix",
            'Channel',
            'Chaos Warp',
            'Char',
            'Chrome Mox',
            'City of Traitors',
            'Clifftop Retreat',
            'Cloudgoat Ranger',
            'Cloudthresher',
            'Coalition Relic',
            'Cold-Eyed Selkie',
            'Coldsteel Heart',
            'Compulsive Research',
            'Condemn',
            'Consecrated Sphinx',
            'Consuming Vapors',
            'Control Magic',
            'Corpse Dance',
            'Counterspell',
            'Countryside Crusher',
            'Creakwood Liege',
            'Creeping Tar Pit',
            'Crucible of Worlds',
            'Cruel Ultimatum',
            'Cryptic Command',
            'Cultivate',
            'Cursecatcher',
            'Cursed Scroll',
            'Damnation',
            'Dark Confidant',
            'Dark Ritual',
            'Dauthi Horror',
            'Day of Judgment',
            'Daybreak Ranger',
            'Daze',
            'Deathmark',
            'Decree of Justice',
            'Decree of Pain',
            'Deep Analysis',
            'Delver of Secrets',
            'Demonic Rising',
            'Demonic Taskmaster',
            'Demonic Tutor',
            'Deprive',
            'Deranged Hermit',
            'Desertion',
            'Desolate Lighthouse',
            'Despise',
            'Devastating Dreams',
            "Devil's Play",
            'Devoted Druid',
            'Diabolic Edict',
            'Diabolic Servitude',
            'Diregraf Ghoul',
            'Disenchant',
            'Dismantling Blow',
            'Dismember',
            'Dismiss',
            'Dissipate',
            'Doom Blade',
            'Doran, the Siege Tower',
            'Dragonskull Summit',
            'Dream Halls',
            'Drogskol Reaver',
            'Drowned Catacomb',
            'Dungeon Geists',
            'Duress',
            'Earthquake',
            'Edric, Spymaster of Trest',
            'Eight-and-a-Half-Tails',
            'Eldrazi Monument',
            'Electrolyze',
            'Elesh Norn, Grand Cenobite',
            'Elite Vanguard',
            'Elspeth Tirel',
            'Elspeth, Knight-Errant',
            'Elves of Deep Shadow',
            'Ember Hauler',
            'Emeria Angel',
            'Empty the Warrens',
            'Enclave Cryptologist',
            'Engineered Explosives',
            'Enlightened Tutor',
            'Entomb',
            'Epochrasite',
            'Esper Charm',
            'Essence Scatter',
            'Etched Oracle',
            'Eternal Dragon',
            'Eternal Witness',
            'Ethersworn Canonist',
            'Everflowing Chalice',
            'Exalted Angel',
            'Exhume',
            'Explore',
            'Fact or Fiction',
            "Faith's Fetters",
            'Falkenrath Aristocrat',
            'Farseek',
            'Fathom Seer',
            'Fauna Shaman',
            'Fellwar Stone',
            'Fertile Ground',
            'Fettergeist',
            'Fiend Hunter',
            'Figure of Destiny',
            'Fireblast',
            'Firemane Angel',
            'Firespout',
            'Firestorm',
            'Flametongue Kavu',
            'Flashfreeze',
            'Flickerwisp',
            'Flooded Strand',
            'Forbid',
            'Forbidden Alchemy',
            'Force of Will',
            'Force Spike',
            'Frantic Search',
            'Frenzied Goblin',
            'Frost Titan',
            'Future Sight',
            'Fyndhorn Elves',
            "Gaea's Cradle",
            'Gamble',
            'Garruk Relentless',
            'Garruk Wildspeaker',
            'Garruk, Primal Hunter',
            'Gatekeeper of Malakir',
            'Gathan Raiders',
            'Geist of Saint Traft',
            'Genesis',
            'Genesis Wave',
            'Genju of the Spires',
            "Geralf's Messenger",
            'Ghitu Encampment',
            'Giant Solifuge',
            'Gideon Jura',
            "Gideon's Lawkeeper",
            'Gifts Ungiven',
            'Gilded Lotus',
            'Glacial Fortress',
            'Glen Elendra Archmage',
            'Gloom Surgeon',
            'Glorious Anthem',
            'Go for the Throat',
            'Goblin Goon',
            'Goblin Guide',
            'Goblin Legionnaire',
            'Goblin Ruinblaster',
            'Goblin Trenches',
            'Goblin Welder',
            'Godless Shrine',
            'Grafted Wargear',
            'Grand Arbiter Augustin IV',
            'Grave Titan',
            'Graveborn Muse',
            'Gravecrawler',
            'Great Sable Stag',
            'Greater Gargadon',
            "Green Sun's Zenith",
            'Grim Lavamancer',
            'Grim Monolith',
            'Grimgrin, Corpse-Born',
            'Griselbrand',
            'Guul Draz Assassin',
            'Hallowed Fountain',
            'Harmonize',
            'Havengul Lich',
            'Headhunter',
            'Heartbeat of Spring',
            "Hell's Thunder",
            'Hellrider',
            'Hellspark Elemental',
            'Hero of Bladehold',
            'Hero of Oxid Ridge',
            'Hex Parasite',
            'Hinterland Harbor',
            'Hokori, Dust Drinker',
            'Honor of the Pure',
            'Huntmaster of the Fells',
            'Hymn to Tourach',
            'Hypnotic Specter',
            'Hystrodon',
            'Ideas Unbound',
            'Imperial Seal',
            'Impulse',
            'Incinerate',
            'Increasing Devotion',
            'Indrik Stomphowler',
            'Inferno Titan',
            'Ingot Chewer',
            'Ink-Eyes, Servant of Oni',
            'Innocent Blood',
            'Inquisition of Kozilek',
            'Into the Roil',
            'Intuition',
            'Isamaru, Hound of Konda',
            'Isochron Scepter',
            'Isolated Chapel',
            'Jace Beleren',
            'Jace, the Mind Sculptor',
            'Jackal Pup',
            'Jade Mage',
            'Jokulhaups',
            'Joraga Treespeaker',
            'Journey to Nowhere',
            'Jushi Apprentice',
            'Kami of Ancient Law',
            'Karakas',
            'Kargan Dragonlord',
            'Karn Liberated',
            'Keiga, the Tide Star',
            'Keldon Champion',
            'Keldon Marauders',
            'Kira, Great Glass-Spinner',
            'Kird Ape',
            'Kitchen Finks',
            'Kjeldoran Outpost',
            'Knight of the Reliquary',
            "Kodama's Reach",
            'Korlash, Heir to Blackblade',
            'Koth of the Hammer',
            'Kozilek, Butcher of Truth',
            'Krosan Grip',
            'Lake of the Dead',
            'Land Tax',
            "Laquatus's Champion",
            'Lavaclaw Reaches',
            'Lead the Stampede',
            'Leatherback Baloth',
            'Leonin Relic-Warder',
            'Lightning Bolt',
            'Lightning Greaves',
            'Lightning Helix',
            'Liliana of the Veil',
            'Liliana Vess',
            'Lingering Souls',
            "Lion's Eye Diamond",
            'Living Death',
            'Llanowar Elves',
            'Loam Lion',
            'Lodestone Golem',
            'Lone Revenant',
            'Looter il-Kor',
            'Lotus Bloom',
            'Lotus Cobra',
            'Lotus Petal',
            'Loxodon Hierarch',
            'Loyal Cathar',
            'Luminarch Ascension',
            'Maelstrom Pulse',
            'Magma Jet',
            'Makeshift Mannequin',
            "Man-o'-War",
            'Mana Leak',
            'Mana Tithe',
            'Manriki-Gusari',
            'Marsh Flats',
            'Martial Coup',
            'Massacre Wurm',
            'Master of the Wild Hunt',
            'Masticore',
            'Maze of Ith',
            'Meloku the Clouded Mirror',
            'Memory Jar',
            'Memory Lapse',
            'Mentor of the Meek',
            'Mesmeric Fiend',
            'Mikaeus, the Lunarch',
            'Mimic Vat',
            'Mind Stone',
            "Mind's Desire",
            'Mindslaver',
            "Mirari's Wake",
            'Mirran Crusader',
            'Mirror Entity',
            'Miscalculation',
            "Mishra's Factory",
            'Misty Rainforest',
            'Mogg War Marshal',
            'Mold Shambler',
            'Moldervine Cloak',
            'Molten Rain',
            'Molten-Tail Masticore',
            "Moment's Peace",
            'Momentary Blink',
            'Mortarpod',
            'Mortify',
            'Mother of Runes',
            'Mox Diamond',
            'Mulldrifter',
            'Mutavault',
            'Myr Battlesphere',
            'Mystic Snake',
            'Mystical Tutor',
            'Nantuko Vigilante',
            'Narcolepsy',
            'Natural Order',
            'Naturalize',
            'Necromancy',
            'Necropotence',
            'Negate',
            'Nekrataal',
            "Nevinyrral's Disk",
            'Nezumi Graverobber',
            'Nezumi Shortfang',
            'Nicol Bolas, Planeswalker',
            "Night's Whisper",
            'Ninja of the Deep Hours',
            'Niv-Mizzet, the Firemind',
            'Noble Hierarch',
            'Nostalgic Dreams',
            'Nucklavee',
            'Obliterate',
            'Oblivion Ring',
            'Obstinate Baloth',
            'Ohran Viper',
            'Okiba-Gang Shinobi',
            'Old Man of the Sea',
            'Olivia Voldaren',
            "Oona's Prowler",
            'Opposition',
            'Opt',
            'Oracle of Mul Daya',
            'Orcish Lumberjack',
            'Oust',
            'Overgrown Tomb',
            'Overrun',
            'Pact of Negation',
            'Paladin en-Vec',
            'Palinchron',
            'Palladium Myr',
            'Parallax Wave',
            'Path to Exile',
            'Pernicious Deed',
            'Persecute',
            'Phantasmal Bear',
            'Phantasmal Image',
            'Phantom Centaur',
            'Phyrexian Arena',
            'Phyrexian Crusader',
            'Phyrexian Metamorph',
            'Phyrexian Obliterator',
            'Phyrexian Processor',
            'Phyrexian Rager',
            'Phyrexian Revoker',
            'Pillage',
            'Pillar of Flame',
            'Pithing Needle',
            'Plague Sliver',
            'Plateau',
            'Plated Geopede',
            'Platinum Angel',
            'Plow Under',
            'Polluted Delta',
            'Ponder',
            'Porcelain Legionnaire',
            'Powder Keg',
            'Power Sink',
            'Precursor Golem',
            'Preordain',
            'Prey Upon',
            'Price of Progress',
            'Priest of Urabrask',
            'Primal Command',
            'Primeval Titan',
            'Primordial Hydra',
            'Prismatic Lens',
            'Pristine Talisman',
            'Profane Command',
            'Prophetic Bolt',
            'Psychatog',
            'Pulse of the Fields',
            'Pulse of the Forge',
            'Puppeteer Clique',
            'Putrefy',
            'Putrid Imp',
            'Putrid Leech',
            'Pyroclasm',
            'Pyrokinesis',
            'Qasali Pridemage',
            'Raging Ravine',
            'Rampant Growth',
            'Rancor',
            'Ranger of Eos',
            'Ratchet Bomb',
            'Ravages of War',
            'Ravenous Baboons',
            'Ray of Revelation',
            'Razormane Masticore',
            'Realm Razer',
            'Reanimate',
            'Reckless Charge',
            'Recurring Nightmare',
            'Red Elemental Blast',
            'Regrowth',
            'Relic of Progenitus',
            'Remand',
            'Renewed Faith',
            'Repeal',
            'Restock',
            'Restoration Angel',
            'Reveillark',
            'Rhox War Monk',
            'Rift Bolt',
            'Riftwing Cloudskate',
            'Rishadan Port',
            'Rite of Ruin',
            'Rofellos, Llanowar Emissary',
            'Rolling Earthquake',
            'Rootbound Crag',
            'Rorix Bladewing',
            'Rout',
            'Rude Awakening',
            'Ruhan of the Fomori',
            'Sacred Foundry',
            'Sakura-Tribe Elder',
            'Sarcomancy',
            'Sarkhan the Mad',
            'Savannah',
            'Savannah Lions',
            'Scalding Tarn',
            'Scavenging Ooze',
            'Scorned Villager',
            'Scroll Rack',
            'Scrubland',
            'Sea Gate Oracle',
            'Seal of Primordium',
            'Search for Tomorrow',
            'Searing Blaze',
            'Seething Song',
            "Sensei's Divining Top",
            'Serendib Efreet',
            'Shadowmage Infiltrator',
            'Shelldock Isle',
            'Sheoldred, Whispering One',
            'Shining Shoal',
            'Show and Tell',
            'Shriekmaw',
            'Shrine of Burning Rage',
            'Siege-Gang Commander',
            'Sigarda, Host of Herons',
            'Silent Specter',
            'Silver Knight',
            'Silverblade Paladin',
            'Simic Sky Swallower',
            'Sinkhole',
            'Skinrender',
            'Skithiryx, the Blight Dragon',
            'Skittering Skirge',
            'Skullclamp',
            'Slagstorm',
            'Slaughter Pact',
            "Slayers' Stronghold",
            'Slith Firewalker',
            'Smash to Smithereens',
            'Smokestack',
            'Snapcaster Mage',
            'Sneak Attack',
            'Snuff Out',
            'Solemn Simulacrum',
            'Soltari Champion',
            'Soltari Monk',
            'Soltari Priest',
            'Somberwald Sage',
            'Sorin, Lord of Innistrad',
            'Sower of Temptation',
            'Spectral Lynx',
            'Spectral Procession',
            'Spell Pierce',
            'Spellskite',
            'Sphere of the Suns',
            'Sphinx of Jwar Isle',
            'Sphinx of the Steel Wind',
            'Spikeshot Elder',
            'Spinning Darkness',
            'Spiritmonger',
            'Sprouting Thrinax',
            'Staggershock',
            'Steam Vents',
            'Steppe Lynx',
            'Stifle',
            'Stillmoon Cavalier',
            'Stirring Wildwood',
            'Stomping Ground',
            'Stonecloaker',
            'Stoneforge Mystic',
            'Stormblood Berserker',
            'Strangleroot Geist',
            'Strip Mine',
            'Student of Warfare',
            'Stunted Growth',
            'Stupor',
            'Sulfur Falls',
            'Sulfuric Vortex',
            'Sun Titan',
            'Sundering Titan',
            'Sunpetal Grove',
            'Survival of the Fittest',
            'Sword of Body and Mind',
            'Sword of Feast and Famine',
            'Sword of Fire and Ice',
            'Sword of Light and Shadow',
            'Sword of War and Peace',
            'Swords to Plowshares',
            'Sylvan Library',
            'Taiga',
            'Tamiyo, the Moon Sage',
            'Tandem Lookout',
            'Tangle Wire',
            'Tarmogoyf',
            'Tattermunge Maniac',
            'Taurean Mauler',
            'Tectonic Edge',
            'Teetering Peaks',
            'Temple Garden',
            'Temporal Mastery',
            'Tendrils of Agony',
            'Terastodon',
            'Terminate',
            'Terminus',
            'Terror',
            'Thalia, Guardian of Thraben',
            'Thawing Glaciers',
            'Thelonite Hermit',
            'Thirst for Knowledge',
            'Thornling',
            'Thornscape Battlemage',
            'Thoughtseize',
            'Thran Dynamo',
            'Throat Slitter',
            'Thrun, the Last Troll',
            'Thunderblust',
            'Thunderscape Battlemage',
            'Tibalt, the Fiend-Blooded',
            'Tidehollow Sculler',
            'Tidings',
            'Time Spiral',
            'Tin Street Hooligan',
            'Tinker',
            'Tithe',
            'Tolaria West',
            'Tombstalker',
            'Tooth and Nail',
            'Torch Fiend',
            "Tormod's Crypt",
            'Tradewind Rider',
            'Tragic Slip',
            'Treachery',
            'Treetop Village',
            'Trinket Mage',
            'Troll Ascetic',
            'Tropical Island',
            'Trygon Predator',
            'Tumble Magnet',
            'Tundra',
            'Turnabout',
            'Ulamog, the Infinite Gyre',
            'Ulvenwald Tracker',
            "Umezawa's Jitte",
            'Unburial Rites',
            'Underground Sea',
            'Undermine',
            'Unearth',
            'Upheaval',
            'Urabrask the Hidden',
            'Urborg, Tomb of Yawgmoth',
            'Vampire Hexmage',
            'Vampire Nighthawk',
            'Vampiric Tutor',
            'Vedalken Shackles',
            'Vendilion Clique',
            'Vengevine',
            'Venser, Shaper Savant',
            'Venser, the Sojourner',
            'Verdant Catacombs',
            'Vesuvan Shapeshifter',
            'Vexing Devil',
            'Vindicate',
            'Vinelasher Kudzu',
            'Vines of Vastwood',
            'Visara the Dreadful',
            'Void',
            'Voidmage Prodigy',
            'Voidslime',
            'Volcanic Fallout',
            'Volcanic Hammer',
            'Volcanic Island',
            'Vulshok Refugee',
            'Wake Thrasher',
            'Wall of Blossoms',
            'Wall of Omens',
            'Wall of Reverence',
            'Wall of Roots',
            'Wasteland',
            'Watery Grave',
            'Weathered Wayfarer',
            'Werebear',
            'Wheel of Fortune',
            'Whipcorder',
            'White Knight',
            'Wickerbough Elder',
            'Wild Nacatl',
            'Wildfire',
            'Willbender',
            'Windbrisk Heights',
            'Windswept Heath',
            'Wispmare',
            'Wolfir Silverheart',
            'Wooded Foothills',
            'Woodfall Primus',
            'Woodland Cemetery',
            'Woolly Thoctar',
            'Worn Powerstone',
            'Worship',
            'Wrath of God',
            'Wrench Mind',
            'Wurmcoil Engine',
            'Xiahou Dun, the One-Eyed',
            'Yavimaya Elder',
            'Yavimaya Hollow',
            "Yawgmoth's Will",
            'Yosei, the Morning Star',
            'Zo-Zu the Punisher',
            'Zombie Cutthroat'
        ]

    def test_card_heuristics(self):
        # this inserts if and only if it's needed
        get_cards_from_names('Lingering Souls')
        c = Client()
        response = c.get('/heuristics/', {}, "text/json",
                         HTTP_X_REQUESTED_WITH='XMLHttpRequest')
        content = response.content
        self.assertIn('token_spells_are_creatures', content)
        self.assertIn('off_color_flashback_is_gold', content)

    def test_contents_handling_reinserts(self):

        c = Client()
        data = self.make_diff_data(['AEther Adept'])
        self.post_to_card_contents(data, c)
        # there shouldn't be problems reinserting
        self.post_to_card_contents(data, c)

    def test_contents_handling_duplicates_on_new_insert(self):

        self.post_to_card_contents(self.make_diff_data(['Gravecrawler'] * 3))

    def test_contents_handling_duplicates_on_new_insert_with_mismatches(self):

        self.post_to_card_contents(self.make_diff_data(['AEther Adept',
                                                        'Aether Adept',
                                                        'aether adept']))

    def test_contents_handling_duplicates_on_fetch(self):
        get_cards_from_names('Gravecrawler')
        self.post_to_card_contents(self.make_diff_data(['Gravecrawler'] * 3))

    def test_contents_handling_duplicates_on_fetch_with_mismatches(self):
        get_cards_from_names('AEther Adept')
        self.post_to_card_contents(self.make_diff_data(['AEther Adept',
                                                        'AEther Adept',
                                                        'Aether Adept',
                                                        'aether adept']))

    def card_contents_everything(self):
        """
        this takes about 4-5 minutes as of 2013-03-11 - it'd be useful to have
        a benchmark here for performance, but I don't think this is a good
        unit test right now
        """

        c = Client()
        data = {'card_names': {
            'after': self.mtgo_avr_cube,
            'before': self.mtgo_og_cube}
        }
        response = c.post('/card_contents/', json.dumps(data), "text/json",
                          HTTP_X_REQUESTED_WITH='XMLHttpRequest')
        # there shouldn't be problems reinserting
        response = c.post('/card_contents/', json.dumps(data), "text/json",
                          HTTP_X_REQUESTED_WITH='XMLHttpRequest')

